# service specific settings for the application.
# those are the default servers which the applications knows about
servers:
  - name: devvm
    serverAddress: 192.168.33.15
    serverPort: 700

  - name: devvm2
    serverAddress: 192.168.33.20
    serverPort: 701


# dropwizard specific configuration
logging:
  level: info

  console:
    enabled: true

